### ISSUE TITLE
Build fails on arm64: An error occurred while building with CMake.

### ISSUE THREAD

**Issue by yurivict** [maxbachmann/rapidfuzz#215]
```
ninja: build stopped: subcommand failed.
  File "/usr/local/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/usr/local/lib/python3.8/site-packages/skbuild/cmaker.py", line 660, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/usr/local/lib/python3.8/site-packages/skbuild/cmaker.py", line 684, in make_impl
    raise SKBuildError(
An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release --
  Install target:
    install
  Source directory:
    /wrkdirs/usr/ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.11
  Working directory:
    /wrkdirs/usr/ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.11/_skbuild/freebsd-13.0-RELEASE-p11-arm64-3.8/cmake-build
Please check the install target is valid and see CMake's output for more information.


--------------------------------------------------------------------------------
-- Trying "Ninja" generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying "Ninja" generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    /wrkdirs/usr/ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.11/_skbuild/freebsd-13.0-RELEASE-p11-arm64-3.8/cmake-build
  Command:
    cmake /wrkdirs/usr/ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.11 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/wrkdirs/usr/ports/devel/py-rapidfuzz/work-py38/rapidfuzz-2.0.11/_skbuild/freebsd-13.0-RELEASE-p11-arm64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3.8 -DPYTHON_VERSION_STRING:STRING=3.8.13 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/usr/local/lib/libpython3.8.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/usr/local/lib/python3.8/site-packages/skbuild/resources/cmake -DRF_CAPI_PATH:STRING=/usr/local/lib/python3.8/site-packages/rapidfuzz_capi -DCMAKE_BUILD_TYPE:STRING=Release

Traceback (most recent call last):

*** Error code 1
```

This failure occurs only on arm64, and not on amd64.

Version: 2.0.11
OS: FreeBSD 13

**Comment by maxbachmann** [comment]
Is this a regression, or did the same error occur in previous versions of RapidFuzz?

**Comment by yurivict** [comment]
I don't have information about previous versions' behavior.

**Comment by maxbachmann** [comment]
I am not really sure how this can be fixed. Since I do not have access to any arm64 free bsd machine, I am unable to test this.

**Comment by Syrus** [comment]
The 2.0.10 version is available on PyPI for arm64. Current version is not. Also, conda-forge version for arm64 is broken. I'm using rapidfuzz on a t4g Graviton instance on EC2 for work, and I ran into the issue using both mamba and pip to install. Had to step back to 2.0.10 to fix the installation errors. What can I do to help identify the issue?

**Comment by Syrus** [comment]
Correction: 2.0.11 is installable via pip, apparently, but I get hash mismatch errors when installing that version using pip.

**Comment by maxbachmann** [comment]
@yurivict could you check whether this issue persists with the latest version of rapidfuzz?

**Comment by yurivict** [comment]
I removed the BROKEN line for arm64 and updated the port.
Would reopen if fallout messages would be coming again.
(I don't have access to arm64 hw to build on-demand.)

Thanks!
