### ISSUE TITLE
Error installing on Termux (arm64)

### ISSUE THREAD

**Issue by cobalt2727** [maxbachmann/rapidfuzz#217]
Error log:
```bash
~ $ pip install rapidfuzz                                                        Collecting rapidfuzz
  Downloading rapidfuzz-2.0.11.tar.gz (904 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 904.2/904.2 kB 747.6 kB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1                                                                   ╰─> [342 lines of output]
      Collecting setuptools>=42
        Downloading setuptools-62.2.0-py3-none-any.whl (1.1 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 694.2 kB/s eta 0:00:00                                                                                   Collecting wheel
        Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting scikit-build>=0.13.0
        Downloading scikit_build-0.14.1-py2.py3-none-any.whl (76 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6 kB 1.9 MB/s eta 0:00:00
      Collecting cmake
        Downloading cmake-3.22.4.tar.gz (31 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting ninja
        Downloading ninja-1.10.2.3.tar.gz (26 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting oldest-supported-numpy
        Downloading oldest_supported_numpy-2022.4.18-py3-none-any.whl (3.9 kB)
      Collecting Cython==3.0.0a10
        Downloading Cython-3.0.0a10-py2.py3-none-any.whl (1.1 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 772.5 kB/s eta 0:00:00
      Collecting rapidfuzz_capi==1.0.5
        Downloading rapidfuzz_capi-1.0.5-py3-none-any.whl (5.8 kB)
      Collecting packaging
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting distro
        Using cached distro-1.7.0-py3-none-any.whl (20 kB)
      Collecting numpy==1.21.6
        Downloading numpy-1.21.6.zip (10.3 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 1.0 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      Building wheels for collected packages: cmake, ninja, numpy
        Building wheel for cmake (pyproject.toml): started
        Building wheel for cmake (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for cmake (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [9 lines of output]
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-wdkhhldn/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
                cmkr = cmaker.CMaker(cmake_executable)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-wdkhhldn/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-wdkhhldn/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
                raise SKBuildError(
            Traceback (most recent call last):

            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
        Building wheel for ninja (pyproject.toml): started
        Building wheel for ninja (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for ninja (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [9 lines of output]
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-1z5dneqt/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
                cmkr = cmaker.CMaker(cmake_executable)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-1z5dneqt/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-1z5dneqt/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
                raise SKBuildError(
            Traceback (most recent call last):

            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for ninja
        Building wheel for numpy (pyproject.toml): started
        Building wheel for numpy (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for numpy (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [242 lines of output]
            setup.py:63: RuntimeWarning: NumPy 1.21.6 may not yet support Python 3.10.
              warnings.warn(
            Running from numpy source directory.
            /data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/tools/cythonize.py:69: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
              from distutils.version import LooseVersion
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/_generator.pyx
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/_common.pyx
            Processing numpy/random/_philox.pyx
            Processing numpy/random/_mt19937.pyx
            Processing numpy/random/bit_generator.pyx
            Processing numpy/random/_pcg64.pyx
            Processing numpy/random/mtrand.pyx
            Cythonizing sources
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            blis_info:
              libraries blis not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            openblas_info:
              libraries openblas not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            accelerate_info:
              NOT AVAILABLE

            atlas_3_10_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries tatlas not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            atlas_3_10_blas_info:
              libraries satlas not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            atlas_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries ptf77blas,ptcblas,atlas not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            atlas_blas_info:
              libraries f77blas,cblas,atlas not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            /data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/system_info.py:2026: UserWarning:
                Optimized (vendor) Blas libraries are not found.
                Falls back to netlib Blas library which has worse performance.
                A better performance should be easily gained by switching
                Blas library.
              if self._calc_info(blas):
            blas_info:
              libraries blas not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            /data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/system_info.py:2026: UserWarning:
                Blas (http://www.netlib.org/blas/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [blas]) or by setting
                the BLAS environment variable.
              if self._calc_info(blas):
            blas_src_info:
              NOT AVAILABLE

            /data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/system_info.py:2026: UserWarning:
                Blas (http://www.netlib.org/blas/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [blas_src]) or by setting
                the BLAS_SRC environment variable.
              if self._calc_info(blas):
              NOT AVAILABLE

            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
              libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            openblas_lapack_info:
              libraries openblas not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            openblas_clapack_info:
              libraries openblas,lapack not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            flame_info:
              libraries flame not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            atlas_3_10_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib
              libraries tatlas,tatlas not found in /data/data/com.termux/files/usr/lib
            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
              NOT AVAILABLE

            atlas_3_10_info:
              libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib
              libraries satlas,satlas not found in /data/data/com.termux/files/usr/lib
            <class 'numpy.distutils.system_info.atlas_3_10_info'>
              NOT AVAILABLE

            atlas_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib
              libraries ptf77blas,ptcblas,atlas not found in /data/data/com.termux/files/usr/lib
            <class 'numpy.distutils.system_info.atlas_threads_info'>
              NOT AVAILABLE

            atlas_info:
              libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib
              libraries f77blas,cblas,atlas not found in /data/data/com.termux/files/usr/lib
            <class 'numpy.distutils.system_info.atlas_info'>
              NOT AVAILABLE

            lapack_info:
              libraries lapack not found in ['/data/data/com.termux/files/usr/lib']
              NOT AVAILABLE

            /data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/system_info.py:1858: UserWarning:
                Lapack (http://www.netlib.org/lapack/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [lapack]) or by setting
                the LAPACK environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()
            lapack_src_info:
              NOT AVAILABLE

            /data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/system_info.py:1858: UserWarning:
                Lapack (http://www.netlib.org/lapack/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [lapack_src]) or by setting
                the LAPACK_SRC environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()
              NOT AVAILABLE

            numpy_linalg_lapack_lite:
              FOUND:
                language = c
                define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

            Warning: attempted relative import with no known parent package
            /data/data/com.termux/files/usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            build_src
            building py_modules sources
            creating build
            creating build/src.linux-aarch64-3.10
            creating build/src.linux-aarch64-3.10/numpy
            creating build/src.linux-aarch64-3.10/numpy/distutils
            building library "npymath" sources
            Could not locate executable gfortran
            Could not locate executable f95
            Could not locate executable ifort
            Could not locate executable ifc
            Could not locate executable lf95
            Could not locate executable pgfortran
            Could not locate executable nvfortran
            Could not locate executable f90
            Could not locate executable f77
            Could not locate executable fort
            Could not locate executable efort
            Could not locate executable efc
            Could not locate executable g77
            Could not locate executable g95
            Could not locate executable pathf95
            Could not locate executable nagfor
            Could not locate executable frt
            don't know how to compile Fortran code on platform 'posix'


            [Errno 2] No such file or directory: 'aarch64-linux-android-clang'


            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/tmpn2qwis92_in_process.py", line 363, in <module>
                main()
              File "/data/data/com.termux/files/usr/tmp/tmpn2qwis92_in_process.py", line 345, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/data/data/com.termux/files/usr/tmp/tmpn2qwis92_in_process.py", line 261, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-dh199d_i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 230, in build_wheel
                return self._build_with_temp_dir(['bdist_wheel'], '.whl',
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-dh199d_i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
                self.run_setup()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-dh199d_i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 267, in run_setup
                super(_BuildMetaLegacyBackend,
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-dh199d_i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 448, in <module>
                setup_package()
              File "setup.py", line 440, in setup_package
                setup(**metadata)
              File "/data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/core.py", line 169, in setup
                return old_setup(**new_attr)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-dh199d_i/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
                return distutils.core.setup(**attrs)
              File "/data/data/com.termux/files/usr/lib/python3.10/distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/data/data/com.termux/files/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
                self.run_command(cmd)
              File "/data/data/com.termux/files/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-dh199d_i/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/data/data/com.termux/files/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/command/build.py", line 61, in run
                old_build.run(self)
              File "/data/data/com.termux/files/usr/lib/python3.10/distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/data/data/com.termux/files/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()
              File "/data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/command/build_src.py", line 155, in build_sources
                self.build_library_sources(*libname_info)
              File "/data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/command/build_src.py", line 288, in build_library_sources
                sources = self.generate_sources(sources, (lib_name, build_info))
              File "/data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/distutils/command/build_src.py", line 378, in generate_sources
                source = func(extension, build_dir)
              File "/data/data/com.termux/files/usr/tmp/pip-install-eygjrm24/numpy_ffd2212aad874cd6b9ce4eed5872b61c/numpy/core/setup.py", line 666, in get_mathlib_info
                raise RuntimeError("Broken toolchain: cannot link a simple C program")
            RuntimeError: Broken toolchain: cannot link a simple C program
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build cmake ninja numpy
      ERROR: Could not build wheels for cmake, ninja, numpy, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by maxbachmann** [comment]
This appears to have a couple of issues:
1) the cmake Python package apparently does not build on Termux (this was already reported in https://github.com/maxbachmann/RapidFuzz/issues/195)
2) it appears numpy does not compile on your platform either

At least right now I do not really see a way for me to fix this. I do not think I will be able to fix this at least in the short term, but I would be happy to incorporate a fix in case someone knows how this can be fixed.

**Comment by maxbachmann** [comment]
Possibly you can convince the termux maintainers to package it as a termux package, which could patch out the cmake dependency and use a system installation of it instead.

**Comment by cobalt2727** [comment]
Thanks for your time! I assume there's no (feasible) way to make rapidfuzz use the system cmake then?

**Comment by maxbachmann** [comment]
> I assume there's no (feasible) way to make rapidfuzz use the system cmake then?

It would be simple to use the system cmake by removing the following line:
https://github.com/maxbachmann/RapidFuzz/blob/a9887c123b004466780dc7081ea7fd484c81e3e7/pyproject.toml#L6
However this complicates the installation for anyone else since they would need to manually install cmake.

I am however not aware of any way to detect whether cmake is already installed and only install it when it is not available yet. Maybe it would be possible to create a fork of the cmake package, which checks whether cmake is available in the setup.py :thinking: 
I think I will give this a try ...

**Comment by cobalt2727** [comment]
Well, this is a bit hacky, but you could test for the command itself:
```python
import os
os.system("command -v cmake")
```
`os.system` spits out an exit code of 0 if it succeeds...

**Comment by jcfr** [comment]
Thanks for reporting the issue upstream and pinging :pray: 

I will post comment directly in the issue so that we can make progress on this and ultimately have a wheel working for termux.
