### ISSUE TITLE
2.13.3: test suite is failing because it cannot find `tests.common`

### ISSUE THREAD

**Issue by kloczek** [maxbachmann/rapidfuzz#297]
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Here is pytest output:
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-rapidfuzz-2.13.3-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-rapidfuzz-2.13.3-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --import-mode=importlib
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.15, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3, configfile: pyproject.toml, testpaths: tests
plugins: hypothesis-6.58.2
collected 75 items / 11 errors

================================================================================== ERRORS ==================================================================================
___________________________________________________________________ ERROR collecting tests/test_fuzz.py ____________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/test_fuzz.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_fuzz.py:7: in <module>
    from .common import symmetric_scorer_tester, scorer_tester
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
________________________________________________________ ERROR collecting tests/distance/test_DamerauLevenshtein.py ________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/distance/test_DamerauLevenshtein.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/distance/test_DamerauLevenshtein.py:4: in <module>
    from ..common import GenericScorer
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
_____________________________________________________________ ERROR collecting tests/distance/test_Hamming.py ______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/distance/test_Hamming.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/distance/test_Hamming.py:2: in <module>
    from ..common import GenericScorer
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
______________________________________________________________ ERROR collecting tests/distance/test_Indel.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/distance/test_Indel.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/distance/test_Indel.py:2: in <module>
    from ..common import GenericScorer
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
_______________________________________________________________ ERROR collecting tests/distance/test_Jaro.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/distance/test_Jaro.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/distance/test_Jaro.py:4: in <module>
    from ..common import GenericScorer
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
___________________________________________________________ ERROR collecting tests/distance/test_JaroWinkler.py ____________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/distance/test_JaroWinkler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/distance/test_JaroWinkler.py:4: in <module>
    from ..common import GenericScorer
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
______________________________________________________________ ERROR collecting tests/distance/test_LCSseq.py ______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/distance/test_LCSseq.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/distance/test_LCSseq.py:2: in <module>
    from ..common import GenericScorer
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
___________________________________________________________ ERROR collecting tests/distance/test_Levenshtein.py ____________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/distance/test_Levenshtein.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/distance/test_Levenshtein.py:3: in <module>
    from ..common import GenericScorer
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
_______________________________________________________________ ERROR collecting tests/distance/test_OSA.py ________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/distance/test_OSA.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/distance/test_OSA.py:2: in <module>
    from ..common import GenericScorer
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
_____________________________________________________________ ERROR collecting tests/distance/test_Postfix.py ______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/distance/test_Postfix.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/distance/test_Postfix.py:2: in <module>
    from ..common import GenericScorer
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
______________________________________________________________ ERROR collecting tests/distance/test_Prefix.py ______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.3/tests/distance/test_Prefix.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/distance/test_Prefix.py:2: in <module>
    from ..common import GenericScorer
E   ModuleNotFoundError: No module named 'tests.common'; 'tests' is not a package
========================================================================= short test summary info ==========================================================================
ERROR tests/test_fuzz.py
ERROR tests/distance/test_DamerauLevenshtein.py
ERROR tests/distance/test_Hamming.py
ERROR tests/distance/test_Indel.py
ERROR tests/distance/test_Jaro.py
ERROR tests/distance/test_JaroWinkler.py
ERROR tests/distance/test_LCSseq.py
ERROR tests/distance/test_Levenshtein.py
ERROR tests/distance/test_OSA.py
ERROR tests/distance/test_Postfix.py
ERROR tests/distance/test_Prefix.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 11 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 11 errors in 1.11s ============================================================================
```
</details>

Here is list of installed modules in build env
<details>

```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
appdirs                       1.4.4
attrs                         22.1.0
Babel                         2.11.0
Brlapi                        0.8.3
build                         0.9.0
charset-normalizer            3.0.1
contourpy                     1.0.6
cssselect                     1.1.0
cycler                        0.11.0
Cython                        0.29.32
distro                        1.8.0
dnspython                     2.2.1
docutils                      0.19
exceptiongroup                1.0.0
extras                        1.0.0
fixtures                      4.0.0
fonttools                     4.38.0
gpg                           1.17.1-unknown
hypothesis                    6.58.2
idna                          3.4
imagesize                     1.4.1
importlib-metadata            5.1.0
iniconfig                     1.1.1
Jinja2                        3.1.2
kiwisolver                    1.4.4
latexcodec                    2.0.1
libcomps                      0.1.19
louis                         3.23.0
lxml                          4.9.1
MarkupSafe                    2.1.1
matplotlib                    3.6.2
numpy                         1.23.1
olefile                       0.46
packaging                     21.3
pbr                           5.9.0
pep517                        0.13.0
Pillow                        9.3.0
pip                           22.3.1
pluggy                        1.0.0
pybtex                        0.24.0
pybtex-docutils               1.0.2
Pygments                      2.13.0
PyGObject                     3.42.2
pyparsing                     3.0.9
pytest                        7.2.0
python-dateutil               2.8.2
pytz                          2022.4
PyYAML                        6.0
requests                      2.28.1
rpm                           4.17.0
scikit-build                  0.16.2
scour                         0.38.2
setuptools                    65.6.3
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
Sphinx                        5.3.0
sphinxcontrib-applehelp       1.0.2.dev20221204
sphinxcontrib-bibtex          2.5.0
sphinxcontrib-devhelp         1.0.2.dev20221204
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20221204
sphinxcontrib-qthelp          1.0.3.dev20221204
sphinxcontrib-serializinghtml 1.1.5
testtools                     2.5.0
tomli                         2.0.1
urllib3                       1.26.12
wheel                         0.38.4
zipp                          3.11.0
```
</details>

**Comment by maxbachmann** [comment]
Hm I am not really sure how to fix this. From my understanding it should be  fine to use a relative import inside the tests using e.g. `from .common import symmetric_scorer_tester`. Do you happen to know how I can import a local file in a way, that would work for your use as well?

**Comment by kloczek** [comment]
Using relative imports is really bad practice and it always causes such issues. Especially using methodology which I've described which sometimes is called "testing as installed" exposes that.
I do not have ATM exact module which imports in tests_*py file some common part.
Will back if I'll find some good exemple.

**Comment by maxbachmann** [comment]
I guess I could change the imports from `from .common import` to `from tests.distance.common import`. Even though I do not know whether this would lead to other issues e.g. when a tests module is installed.

**Comment by kloczek** [comment]
Cannot quicly test that PR because tar ball created from git tag uses as well some submodules and on use sdist tar ball I have some rejectios
```console
+ rm -rf rapidfuzz-2.13.3
+ /usr/bin/gzip -dc /home/tkloczko/rpmbuild/SOURCES/rapidfuzz-2.13.3.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd rapidfuzz-2.13.3
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/python-rapidfuzz-use-absolute-imports-in-tests.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch -f
File extern/rapidfuzz-cpp is not a regular file -- refusing to patch
1 out of 1 hunk ignored -- saving rejects to file extern/rapidfuzz-cpp.rej
The text leading up to this was:
--------------------------
|diff --git a/tests/distance/common.py b/tests/distance/common.py
|index 4bd47e4e..0ae04778 100644
|--- a/tests/distance/common.py
|+++ b/tests/distance/common.py
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
1 out of 1 hunk FAILED -- saving rejects to file tests/distance/test_DamerauLevenshtein.py.rej
1 out of 1 hunk FAILED -- saving rejects to file tests/distance/test_Hamming.py.rej
1 out of 1 hunk FAILED -- saving rejects to file tests/distance/test_Indel.py.rej
1 out of 1 hunk FAILED -- saving rejects to file tests/distance/test_Jaro.py.rej
1 out of 1 hunk FAILED -- saving rejects to file tests/distance/test_JaroWinkler.py.rej
1 out of 1 hunk FAILED -- saving rejects to file tests/distance/test_LCSseq.py.rej
1 out of 1 hunk FAILED -- saving rejects to file tests/distance/test_Levenshtein.py.rej
1 out of 1 hunk FAILED -- saving rejects to file tests/distance/test_OSA.py.rej
1 out of 1 hunk FAILED -- saving rejects to file tests/distance/test_Postfix.py.rej
1 out of 1 hunk FAILED -- saving rejects to file tests/distance/test_Prefix.py.rej
The text leading up to this was:
--------------------------
|diff --git a/tests/distance/test_distance.py b/tests/distance/test_distance.py
|index cc2791a7..89debf3a 100644
|--- a/tests/distance/test_distance.py
|+++ b/tests/distance/test_distance.py
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
```

**Comment by kloczek** [comment]
BTW it would be good to have possibilito to build `rapidfuzz` module against shared `rapidfuzz-cpp` and `taskflow` libraries.

**Comment by maxbachmann** [comment]
> BTW it would be good to have possibilito to build rapidfuzz module against shared rapidfuzz-cpp and taskflow libraries.

This is already possible: https://github.com/maxbachmann/RapidFuzz/blob/88d76ebf919afa0540d7c23feb67d3e7982e1e67/CMakeLists.txt#L74 When available the system version takes precedence over the submodule, which is already used e.g. by Nix. Note that this does not really link against them in a different way, since both of them are header only libraries.

**Comment by kloczek** [comment]
Ha .. ok will try that 😄

**Comment by maxbachmann** [comment]
For reference: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/rapidfuzz/default.nix

**Comment by maxbachmann** [comment]
I uploaded version `2.13.4` with the change

**Comment by kloczek** [comment]
Just tested new version and test suite is now OK 😄 
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-rapidfuzz-2.13.4-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-rapidfuzz-2.13.4-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.16, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/rapidfuzz-2.13.4, configfile: pyproject.toml, testpaths: tests
plugins: hypothesis-6.60.0, anyio-3.6.2
collected 272 items

tests/test_fuzz.py ........................................................................................................................................          [ 50%]
tests/test_hypothesis.py ......................                                                                                                                      [ 58%]
tests/test_process.py ............................                                                                                                                   [ 68%]
tests/test_utils.py .                                                                                                                                                [ 68%]
tests/distance/test_DamerauLevenshtein.py ................                                                                                                           [ 74%]
tests/distance/test_Hamming.py ..                                                                                                                                    [ 75%]
tests/distance/test_Indel.py ..                                                                                                                                      [ 76%]
tests/distance/test_Jaro.py ..                                                                                                                                       [ 76%]
tests/distance/test_JaroWinkler.py ..                                                                                                                                [ 77%]
tests/distance/test_LCSseq.py .                                                                                                                                      [ 77%]
tests/distance/test_Levenshtein.py .......                                                                                                                           [ 80%]
tests/distance/test_OSA.py .....                                                                                                                                     [ 82%]
tests/distance/test_Postfix.py ..                                                                                                                                    [ 83%]
tests/distance/test_Prefix.py ..                                                                                                                                     [ 83%]
tests/distance/test_distance.py ....................                                                                                                                 [ 91%]
tests/distance/test_init.py ........................                                                                                                                 [100%]

=========================================================================== 272 passed in 43.60s ===========================================================================
```
Closing and thank you 👍 

BTW: is it possible to include docs/ content in sdist tar ball on next release? 🤔

**Comment by maxbachmann** [comment]
Sure I can add the docs to the sdist.

**Comment by kloczek** [comment]
On trying build documentation as man page I found that `rapidfuzz` uses `m2r2` module which is no longer maintained.
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 459, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'm2r2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 462, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension m2r2 (exception: No module named 'm2r2')

Extension error:
Could not import extension m2r2 (exception: No module named 'm2r2')
```
It would be good use some replacement.

**Comment by maxbachmann** [comment]
Where did you find, that `m2r2` is not maintained anymore?

**Comment by kloczek** [comment]
Wrong wording.
`m2r2` still is not updated for `mistune` 2.x (on the horizon already is `mistune` 3.x).
https://github.com/CrossNox/m2r2/blob/b714470c89f0749e461daa54c98eca64c60351e9/setup.py#L24
It is kind of blocker 😢

**Comment by maxbachmann** [comment]
:+1: got rid of it, since I only use it to parse my changelog anyways: https://github.com/maxbachmann/RapidFuzz/commit/08c1ecc1b8a1ebcf98bc69bd0619af38f1d51015

**Comment by kloczek** [comment]
Thak you 👍 😄
